global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'Testing first job'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'Testing rabbitmq'
    static_configs:
      - targets: [ 'rabbitmq:15692' ]
